version: "3"

services:
  mongodb:
    image: mongo:4
    ports:
      - 27017:27017
    volumes: 
      - ./data-db:/data/db

  api:
    build: .
    command: npm run dev
    ports: 
      - 3000:3000
    environment: 
      MONGO_URL: mongodb
      PORT: 3000
      NODE_ENV: production
    volumes:
      - ./.:/src/
      - nodemodules:/src/node_modules
    links: 
      - mongodb
    depends_on: 
      - mongodb

volumes: 
  nodemodules: {}
  data-db: {}
