version: "3.7"

services:
  node-ts-otimizado:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: smart-schools-api
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
      - "9229:9229"
    command: npm run dev
